#!/bin/bash
# sauerbraten-server, a systemd service and bash script to manage a Sauerbraten
# (Cube 2) server in the background.
# Copyright (C) 2016  Kevin Boxhoorn
#
# sauerbraten-server is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sauerbraten-server is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sauerbraten-server.  If not, see <http://www.gnu.org/licenses/>.

NAME=sauerbraten-server
GAME_DIR=/usr/games/sauerbraten
GAME_EXEC=linux_64_server
GAME_PATH=$GAME_DIR/bin_unix/$GAME_EXEC
GAME_LOG=/var/log/$NAME.log
GAME_CFG=$GAME_DIR/server-init.cfg
TIMESTAMP=/tmp/timestamp

view_log() {
	tail -f $GAME_LOG
}
do_start() {
	pidof -s $GAME_EXEC > /dev/null
	if [ $? -ne 0 ]; then
		nohup $GAME_PATH -q$GAME_DIR >> $GAME_LOG 2>&1 &
	fi
}
do_stop() {
	kill $(pidof -s $GAME_EXEC)
}
do_restart() {
	do_stop
	do_start
}
edit_cfg() {
	touch $TIMESTAMP
	$EDITOR $GAME_CFG
	if [ $GAME_CFG -nt $TIMESTAMP ]; then
		echo -n Restarting $NAME due to configuration changes
		do_restart
		echo .
	fi
	rm $TIMESTAMP
}

case "$1" in
	start)
		echo -n Starting $NAME
		do_start
		echo .
		;;
	stop)
		echo -n Stopping $NAME
		do_stop
		echo .
		;;
	restart)
		echo -n Restarting $NAME
		do_restart
		echo .
		;;
	run)
		echo -n Running $NAME
		touch $GAME_LOG
		do_start
		echo .
		view_log
		;;
	edit-config)
		edit_cfg
		;;
	*)
		echo Usage: $NAME "{start|stop|restart|run|edit-config}"
		exit 1
		;;
esac
